# ****************************************
# appveyor.yml - Appveyor CI configuration
# ****************************************
# This was based on https://github.com/pyinstaller/pyinstaller/blob/develop/appveyor.yml
environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: 3.3
      PYTHON_ARCH: 32
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c \"import struct; print(struct.calcsize('P') * 8)\"

  # Use setup.py to install dependencies and add CodeChat to the Python path.
  - python setup.py develop

build: none

test_script:
  - py.test
